name: MinecraftUnoRebuilt
version: '0.1'
main: de.crazypokemondev.minecraftUnoRebuilt.MinecraftUnoRebuilt
api-version: '1.21.10'
authors: [ Olfi01 ]
depend:
  - GuiLib
  - UniGUI
softdepend:
  - GSit

permissions:
  uno.deck.give:
    description: "Allows the player to give a UNO deck to anyone via command."
    default: op
    children:
      uno.deck.give.self:
        description: "Allows the player to give a UNO deck only to themselves."
        default: op
